name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Check if JAR file exists
        run: ls -l target/idonate-0.0.1-SNAPSHOT.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-app

      - name: Check downloaded files
        run: ls -l

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.-0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "SSH Connection Successful"

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: idonate-0.0.1-SNAPSHOT.jar
          target: /var/www/idonate-api/idonate.jar

      - name: Restart Spring Boot Service
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart springboot-app