name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

#      - name: Copy files to EC2
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r * ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/idonate-api

      - name: Log in to EC2 via SSH and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "target/idonate-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"
#          script: |
#            cd /home/ubuntu/idonate-api
#            docker build -t idonate-api .
#            docker run -d -p 8080:8080 idonate-api

      - name: Execute SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/sua-aplicacao.jar > /dev/null 2>&1 &
